from typing import Protocol

from vertere_api.veterinarios.domain import Veterinario


class VeterinarioRepository(Protocol):
    def buscar_por_crmv(self, crmv: str) -> Veterinario | None: ...
    def buscar_por_id(self, veterinario_id: str) -> Veterinario | None: ...
    def listar_todas(self) -> list[Veterinario]: ...
    def salvar(self, veterinario: Veterinario) -> None: ...
