from typing import Protocol

from vertere_api.clinicas.domain import Clinica


class ClinicaRepository(Protocol):
    def buscar_por_cnpj(self, cnpj: str) -> Clinica | None: ...
    def buscar_por_id(self, clinica_id: str) -> Clinica | None: ...
    def listar_todas(self) -> list[Clinica]: ...
    def salvar(self, clinica: Clinica) -> None: ...
