from typing import Protocol

from vertere_api.financeiro.domain import Fechamento


class FechamentoRepository(Protocol):
    def buscar_por_id(self, fechamento_id: str) -> Fechamento | None: ...
    def buscar_por_clinica_periodo(self, clinica_id: str, ano: int, mes: int) -> Fechamento | None: ...
    def listar_todas(self) -> list[Fechamento]: ...
    def salvar(self, fechamento: Fechamento) -> None: ...
