"""create veterinarios table

Revision ID: 3cb02521b980
Revises: aeccdc2ed04c
Create Date: 2026-09-20 00:05:45.787686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb02521b980'
down_revision: Union[str, Sequence[str], None] = 'aeccdc2ed04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veterinarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('crmv', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('clinica_id', sa.String(length=36), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veterinarios_crmv'), 'veterinarios', ['crmv'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veterinarios_crmv'), table_name='veterinarios')
    op.drop_table('veterinarios')
    # ### end Alembic commands ###
