"""create fechamentos table and clinicas prazo_pagamento_dias

Revision ID: 5e4f2bb2b0e6
Revises: 5fb56d24d20e
Create Date: 2026-09-21 20:39:46.897104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4f2bb2b0e6'
down_revision: Union[str, Sequence[str], None] = '5fb56d24d20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fechamentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinica_id', sa.String(length=36), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_atendimentos', sa.Integer(), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'ano', 'mes', name='uq_fechamento_clinica_periodo')
    )
    op.add_column('clinicas', sa.Column('prazo_pagamento_dias', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinicas', 'prazo_pagamento_dias')
    op.drop_table('fechamentos')
    # ### end Alembic commands ###
