"""create pacientes table

Revision ID: 683ad9092cc2
Revises: 3cb02521b980
Create Date: 2026-09-20 00:33:36.513878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683ad9092cc2'
down_revision: Union[str, Sequence[str], None] = '3cb02521b980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('especie', sa.String(length=100), nullable=False),
    sa.Column('raca', sa.String(length=100), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('proprietario', sa.String(length=255), nullable=False),
    sa.Column('clinica_id', sa.String(length=36), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    # ### end Alembic commands ###
