"""create exames and regras_plantao tables

Revision ID: ae5622eb5b86
Revises: 683ad9092cc2
Create Date: 2026-09-20 14:07:22.491328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5622eb5b86'
down_revision: Union[str, Sequence[str], None] = '683ad9092cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('preco_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regras_plantao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('valor_adicional', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regras_plantao')
    op.drop_table('exames')
    # ### end Alembic commands ###
