"""create clinicas table

Revision ID: aeccdc2ed04c
Revises: c0f81e669791
Create Date: 2026-09-19 23:07:07.908288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeccdc2ed04c'
down_revision: Union[str, Sequence[str], None] = 'c0f81e669791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinicas_cnpj'), 'clinicas', ['cnpj'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinicas_cnpj'), table_name='clinicas')
    op.drop_table('clinicas')
    # ### end Alembic commands ###
