"""create atendimentos and atendimento_itens_exame tables

Revision ID: b4e3cf8d7186
Revises: ae5622eb5b86
Create Date: 2026-09-20 15:14:24.623044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e3cf8d7186'
down_revision: Union[str, Sequence[str], None] = 'ae5622eb5b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinica_id', sa.String(length=36), nullable=False),
    sa.Column('veterinario_id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.String(length=36), nullable=False),
    sa.Column('metodo_coleta', sa.String(length=100), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('regra_plantao_id', sa.String(length=36), nullable=True),
    sa.Column('valor_adicional_plantao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['regra_plantao_id'], ['regras_plantao.id'], ),
    sa.ForeignKeyConstraint(['veterinario_id'], ['veterinarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimento_itens_exame',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('atendimento_id', sa.String(length=36), nullable=False),
    sa.Column('exame_id', sa.String(length=36), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['exame_id'], ['exames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atendimento_itens_exame')
    op.drop_table('atendimentos')
    # ### end Alembic commands ###
