from typing import Protocol

from vertere_api.exames.domain import Exame, RegraPlantao


class ExameRepository(Protocol):
    def buscar_por_id(self, exame_id: str) -> Exame | None: ...
    def listar_todas(self) -> list[Exame]: ...
    def salvar(self, exame: Exame) -> None: ...


class RegraPlantaoRepository(Protocol):
    def buscar_por_id(self, regra_id: str) -> RegraPlantao | None: ...
    def listar_todas(self) -> list[RegraPlantao]: ...
    def salvar(self, regra: RegraPlantao) -> None: ...
